### ISSUE TITLE
does it support windows?

### ISSUE THREAD

**Issue by qq470647251** [acsone/bobtemplates.odoo#27]
run  on windows10 and python27:

(venv) c:\Users\qq470647251\Desktop>mrbob bobtemplates.odoo:addon

File "d:\p\odoo-11.0\venv\lib\site-packages\bobtemplates\odoo\hooks.py", line 37, in _delete_file
    os.remove(path)
WindowsError: [Error 3] : u'c:\\Users\\qq470647251\\Desktop\\test/README.rst.oca'

**Comment by sbidoul** [comment]
I personally don't directly know anyone using this on windows. But there is not reason it should not work on windows. First thing to check is if mrbob itself works on windows.

PR welcome.

**Comment by qq470647251** [comment]
@sbidoul 
you're right.
mr.bob is not support windows very well.
here is the link:`https://github.com/domenkozar/mr.bob/issues/49`
