### ISSUE TITLE
[RFC] Change templates to take into account black formatting 

### ISSUE THREAD

**Issue by rousseldenis** [acsone/bobtemplates.odoo#30]

**Comment by sbidoul** [comment]
Why not. Not sure it's worth the effort though, because your editor or pre-commit hook will do it anyway for you.

**Comment by rousseldenis** [comment]
Yes, I had that in mind writing this. But, that can decrease changes in pre-commits.

**Comment by ThomasBinsfeld** [comment]
I don't think bobtemplates should be Black-compliant. Plus, Black formatting depends on a project-level config. And i like simple quotes by default in manifests.

**Comment by sbidoul** [comment]
Yes as long as OCA is not black compliant, it's better to stay as close as possible to the OCA template. 
For projects that are black compliant, it's easy enough to blacken the code after template generation.
