### ISSUE TITLE
Would docstring variables be accepted?

### ISSUE THREAD

**Issue by blaggacao** [acsone/bobtemplates.odoo#34]
among others pylint requires / strongly suggests it and could enforce good practice. Not 100% sure if a sensible way of dealing with docstrings can be found in an odoo context, but at least if `inherit == False`, it could be made required.

Encourages thinking before doing ... :wink:

**Comment by sbidoul** [comment]
How would it work in practice?

**Comment by blaggacao** [comment]
No idea... :smile: But as I plan to commit on bob.templates, when time comes... 

Thanks for this project (and others) btw.

**Comment by sbidoul** [comment]
As there is no concrete action here, I'm closing for now.
